apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: petclinic
        image: niveditha223/spring-petclinic:latest   # <-- image comes from Docker Hub
        imagePullPolicy: Always                      # pull each time tag changes
        ports:
          - containerPort: 9090                      # port INSIDE the pod
        readinessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 10
